### ISSUE TITLE
Inkscape 1.0 Extensions

### ISSUE THREAD

**Issue by doctormo** [mnesarco/inkscape-parametric#1]
The new inkscape extensions API for 1.0 has depricated some of the code in use in this extension. It should still work, but with a warning about it being depricated.

simplestyle and similar modules are gone, everything is now in the inkex module. Examples and testing can be found in the new separated repository: https://gitlab.com/inkscape/extensions/tree/master

**Comment by mnesarco** [comment]
Hi @doctormo 
Thank you for the info. The current version of this extension is on Gitlab[1] and it was upgraded to extensions API 1.0.

[1] https://gitlab.com/mnesarco/inkscape-pyscript

**Comment by doctormo** [comment]
:+1:
