### ISSUE TITLE
Manipulate elements too, not only attributes

### ISSUE THREAD

**Issue by meller1190** [mnesarco/inkscape-parametric#2]
Hello,
I wonder if it is planed to update elements as well? "parametric inkscape" works great for attributes. But it would come in handy to be able to change element nodes as well.

E.g. I wanted to implement kind of an auto-updated date/timestamp. In svg-code it is a text element containing a tspan element. 
```
    <text
       xml:space="preserve"
       style="..."
       x="83.571426"
       y="227.3622"
       id="datestamptext">
   <title id="title901">Datestamp</title>
   <tspan
         sodipodi:role="line"
         id="tspan895"
         x="83.571426"
         y="227.3622"
         style="font-weight:bold">Date 2020-02-02
    </tspan>
  </text>
```
So here one would need to update the content of the tspan element (the date text in this case)

**Comment by mnesarco** [comment]
Hi @meller1190 
This repository is outdated, the current version is on Gitlab and it supports full document manipulation and a builtin code editor.

https://gitlab.com/mnesarco/inkscape-pyscript

Cheers!
